#!/usr/bin/env bash

_SROOT="$( cd "$(dirname "$(realpath "$0")")" ; pwd -P )"

PRESETS_DIR="$_SROOT/presets"
CONFIG_FILE="$PRESETS_DIR/mypresets.ini"

# 过滤掉的模型关键词（文生图、视频等 llama.cpp serve 无用的模型）
FILTER_KEYWORDS=(
    "z_image"
    "Wan2.2"
)

mkdir -p "$PRESETS_DIR"

# 检查模型是否应该被过滤
should_filter() {
    local filename="$1"
    for keyword in "${FILTER_KEYWORDS[@]}"; do
        if [[ "$filename" == *"$keyword"* ]]; then
            return 0  # 应该过滤
        fi
    done
    return 1  # 不过滤
}
MODEL_DIRS=(
    "/mnt/volume3/hf_models"
    "/mnt/volume3/modelscope_models"
)

# 清理旧备份文件，保留最近的5个
cleanup_old_backups() {
    local config_file="$1"
    local backup_files=($(ls -t "${config_file}.backup."* 2>/dev/null))
    local total_backups=${#backup_files[@]}
    
    if [[ $total_backups -gt 5 ]]; then
        local files_to_remove=$((total_backups - 5))
        echo -e "${YELLOW}清理旧备份文件，保留最近5个...${NC}"
        
        for ((i=5; i<total_backups; i++)); do
            echo -e "${YELLOW}删除旧备份: ${backup_files[i]}${NC}"
            rm "${backup_files[i]}"
        done
    fi
}

# 颜色输出
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "========================================="
echo "扫描 GGUF 模型文件"
echo "========================================="
echo ""

# 查找所有 gguf 模型
echo "正在扫描以下目录："
for dir in "${MODEL_DIRS[@]}"; do
    if [[ -d "$dir" ]]; then
        echo "  📁 $dir"
    else
        echo -e "${RED}  ❌ 目录不存在: $dir${NC}"
    fi
done
echo ""

# 查找所有 .gguf 文件
gguf_files=()
filtered_count=0
for dir in "${MODEL_DIRS[@]}"; do
    if [[ -d "$dir" ]]; then
        while IFS= read -r -d '' file; do
            filename=$(basename "$file")
            if should_filter "$filename"; then
                ((filtered_count++))
                continue
            fi
            if [[ "$file" != *"/.__"* ]]; then
                gguf_files+=("$file")
            fi
        done < <(find "$dir" -type f -name "*.gguf" -print0 | sort -z)
    fi
done

total_found=${#gguf_files[@]}

if [[ $filtered_count -gt 0 ]]; then
    echo -e "${YELLOW}已过滤 $filtered_count 个模型（文生图/视频模型）${NC}"
fi
echo -e "${GREEN}找到 $total_found 个有效 GGUF 模型文件${NC}"
echo "========================================="
echo ""

# 显示找到的模型
for model in "${gguf_files[@]}"; do
    # 提取模型文件名
    filename=$(basename "$model")
    # 提取相对路径（更简洁的显示）
    for dir in "${MODEL_DIRS[@]}"; do
        if [[ "$model" == "$dir"* ]]; then
            relative_path="${model#$dir/}"
            break
        fi
    done
    echo -e "${GREEN}✓${NC} $filename"
    echo "  路径: $model"
    echo ""
done

# 检查 presets/mypresets.ini 中的模型
echo "========================================="
echo "检查 presets/mypresets.ini 中的模型配置"
echo "========================================="
echo ""

if [[ ! -f "$CONFIG_FILE" ]]; then
    echo -e "${YELLOW}⚠ 配置文件 presets/mypresets.ini 不存在，将创建新文件${NC}"
    touch "$CONFIG_FILE"
fi

# 提取配置文件中的所有模型路径
config_models=$(grep -E "^m\s*=" "$CONFIG_FILE" | sed 's/^m\s*=\s*//' | tr -d ' ')

total_config=0
invalid=0
valid=0
invalid_models=()

while IFS= read -r model_path; do
    if [[ -n "$model_path" ]]; then
        ((total_config++))
        model_name=$(grep -B 1 "$model_path" "$CONFIG_FILE" | grep "^\[" | sed 's/\[//;s/\]//')

        if [[ -f "$model_path" ]]; then
            ((valid++))
            echo -e "${GREEN}✅${NC} $model_name"
        else
            ((invalid++))
            invalid_models+=("$model_name|$model_path")
            echo -e "${RED}❌${NC} $model_name"
            echo "   路径: $model_path"
        fi
    fi
done <<< "$config_models"

echo ""
echo "========================================="
echo "统计结果:"
echo "========================================="
echo "扫描到的模型总数: $total_found"
echo "配置文件中的模型: $total_config"
echo "  有效模型: $valid"
echo "  无效模型: $invalid"
echo ""

if [[ $invalid -gt 0 ]]; then
    echo -e "${RED}无效模型列表:${NC}"
    for model in "${invalid_models[@]}"; do
        name=$(echo "$model" | cut -d'|' -f1)
        path=$(echo "$model" | cut -d'|' -f2)
        echo "  - $name"
        echo "    $path"
    done
    echo ""
fi

# 询问是否生成新的配置文件
if [[ $total_found -gt 0 ]]; then
    echo -e "${YELLOW}是否生成新的 presets/mypresets.ini？（这将覆盖现有配置）[y/N]${NC}"
    read -r response

    if [[ "$response" =~ ^[Yy]$ ]]; then
        echo ""
        echo "正在生成新的 presets/mypresets.ini..."

        # 备份旧配置
        if [[ -f "$CONFIG_FILE" ]]; then
            backup_file="${CONFIG_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
            cp "$CONFIG_FILE" "$backup_file"
            echo -e "${YELLOW}旧配置已备份至: $backup_file${NC}"
            
            cleanup_old_backups "$CONFIG_FILE"
        fi

        # 生成新配置
        {
            echo "# Auto-generated by check_invalid_models.sh"
            echo "# Generated at: $(date)"
            echo "# Total models: $total_found"
            echo ""

            for model in "${gguf_files[@]}"; do
                # 从文件名生成预设名称
                filename=$(basename "$model")
                # 移除 .gguf 扩展名
                name="${filename%.gguf}"
                # 替换特殊字符为连字符
                name=$(echo "$name" | sed 's/[^a-zA-Z0-9._-]/_/g')

                echo "[$name]"
                echo "m = $model"
                echo "temp = 0.7"
                echo "top-p = 0.8"
                echo "top-k = 20"
                echo "min-p = 0"
                echo "ctx-size = 102400"
                echo ""
            done
        } > "$CONFIG_FILE"

        echo -e "${GREEN}✅ 新配置已生成: presets/mypresets.ini${NC}"
    else
        echo "配置文件未修改。"
    fi
fi

echo ""
echo "完成！"
